stages:
  - test

backend-test:
  image: python:3.10
  stage: test
  before_script:
    - cd backend
    - pip install -r requirements.txt
  script:
    - echo "Testing Backend..."
    - python -m pytest
  only: 
    - main
    - fix/gitlab-ci

godot-test:
  image: barichello/godot-ci:latest
  stage: test
  before_script:
    - godot --headless --editor --quit || true  # import assets
  script:
    - echo "Testing Frontend..."
    - godot --headless -s --path "$PWD" addons/gut/gut_cmdln.gd -gdir=res://test/integration -gexit
    - godot --headless -s --path "$PWD" addons/gut/gut_cmdln.gd -gdir=res://test/unit -gexit
  only: 
    - main
    - fix/gitlab-ci
