stages:
  - test

backend-test:
  image: python:3.10
  stage: test
  before_script:
    - cd backend
    - pip install -r requirements.txt
  script:
    - echo "Testing Backend..."
    - python -m pytest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "fix/gitlab-ci" # fix or remove later

godot-test:
  image: barichello/godot-ci:4.4
  stage: test
  before_script:
    - cd sos-game
    - godot --headless --import --quit # import assets
  script:
    - echo "Testing Frontend..."
    - godot --headless -s addons/gut/gut_cmdln.gd -gdir=res://test/integration -gexit
    - godot --headless -s addons/gut/gut_cmdln.gd -gdir=res://test/unit -gexit
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "fix/gitlab-ci" # fix or remove later
